"""empty message

Revision ID: 15983cba976e
Revises: b71131af75f0
Create Date: 2016-11-22 14:53:58.444321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15983cba976e'
down_revision = 'b71131af75f0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_description', sa.String(), nullable=False),
    sa.Column('store_image', sa.String(), nullable=False),
    sa.Column('store_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    ### end Alembic commands ###
