"""empty message

Revision ID: 419eb8b35ef9
Revises: 15983cba976e
Create Date: 2016-11-23 01:13:11.453844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419eb8b35ef9'
down_revision = '15983cba976e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=False),
    sa.Column('store_home', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_home'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    ### end Alembic commands ###
