"""empty message

Revision ID: 539de34e7663
Revises: 
Create Date: 2016-11-23 11:55:37.439685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539de34e7663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_home', sa.Integer(), nullable=True))
    op.drop_constraint(u'products_store_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'store', ['store_home'], ['id'])
    op.drop_column('products', 'store_id')
    op.add_column('store', sa.Column('store_owner', sa.Integer(), nullable=True))
    op.drop_constraint(u'store_user_id_fkey', 'store', type_='foreignkey')
    op.create_foreign_key(None, 'store', 'users', ['store_owner'], ['id'])
    op.drop_column('store', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.create_foreign_key(u'store_user_id_fkey', 'store', 'users', ['user_id'], ['id'])
    op.drop_column('store', 'store_owner')
    op.add_column('products', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(u'products_store_id_fkey', 'products', 'store', ['store_id'], ['id'])
    op.drop_column('products', 'store_home')
    ### end Alembic commands ###
